# Generated by Django 2.1.3 on 2018-12-01 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socnet', '0002_auto_20181201_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='pending',
            field=models.BooleanField(default=True),
        ),
    ]
