# Generated by Django 2.1.3 on 2018-12-01 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socnet', '0004_auto_20181201_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='bbuser',
            name='profile_pic',
            field=models.ForeignKey(blank=True, db_column='profile_pic', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='socnet.Photo'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/events/'),
        ),
        migrations.AddField(
            model_name='photo',
            name='photo',
            field=models.ImageField(default='a', upload_to='photos/photos/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='usr',
            field=models.ForeignKey(db_column='usr', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
