# Generated by Django 2.1.3 on 2018-12-01 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socnet', '0006_auto_20181201_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='content',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
