# Generated by Django 2.1.3 on 2018-12-02 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socnet', '0009_auto_20181202_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='content_ref',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='socnet.Event'),
            preserve_default=False,
        ),
    ]
