# Generated by Django 2.1.3 on 2018-12-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socnet', '0010_content_content_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bbuser',
            name='profile_pic',
            field=models.ImageField(blank=True, db_column='profile_pic', null=True, upload_to='photos/photos/'),
        ),
    ]
