# Generated by Django 2.1.3 on 2018-12-02 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socnet', '0011_auto_20181202_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='albumid',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='photoid',
        ),
        migrations.RemoveField(
            model_name='post',
            name='postid',
        ),
        migrations.AddField(
            model_name='album',
            name='id',
            field=models.OneToOneField(db_column='id', default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='socnet.Content'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='id',
            field=models.OneToOneField(db_column='id', default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='socnet.Content'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='id',
            field=models.OneToOneField(db_column='id', default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='socnet.Content'),
            preserve_default=False,
        ),
    ]
