# Generated by Django 2.1.3 on 2018-12-02 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socnet', '0012_auto_20181202_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='contentid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
